# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MaximumView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1088, 756)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalSlider_frames = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_frames.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_frames.setObjectName("horizontalSlider_frames")
        self.verticalLayout.addWidget(self.horizontalSlider_frames)
        self.label_view = QtWidgets.QLabel(self.centralwidget)
        self.label_view.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_view.setObjectName("label_view")
        self.verticalLayout.addWidget(self.label_view)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_view.setText(_translate("MainWindow", "TextLabel"))
